### ISSUE TITLE
Cant load or save map

### ISSUE THREAD

**Issue by NicholasUchoa** [TEdit/terraria-map-editor-web#1]
I tried to load a map of the latest version but reading the main page i realized that it cant read this map version. So i will have to use another map viewer.

**Comment by RussDev7** [comment]
Would you mind dropping a world download so we can look into this?

**Comment by Elsin10** [comment]
Tried to zip and upload but didn't accept. Sorry for the delay. Didnt read the email.

https://drive.google.com/file/d/15ES_1hPPjpVDDOaH9XhdfqEsJDm4M7Hy/view?usp=sharing

**Comment by GhostDog98** [comment]
Having a very similar issue, I can't load any worlds from my local files, nor do the file -> Example map selections work...
