### ISSUE TITLE
Parsing Problems?

### ISSUE THREAD

**Issue by sebper616** [TEdit/terraria-map-editor-web#6]
I've been trying to upload a map for the purposes of editing, both on mobile (iOS) and on my ChromeBook, but, every time I submit it, making sure that the options to ignore buffer bonds and section offset check each time. In turn, each time I try to load the file, the parsing stage takes so long that it breaks the boundaries of the loading box and disappears offscreen, eventually crashing the page, which the browser declares "Error Label: SIGILL".

For the sake of testing, if necessary, here is the world I'm struggling with:
https://cdn.discordapp.com/attachments/747443084274696214/1107800606309089340/The_Desperate_Garden_2.wld

And here is its backup:
https://cdn.discordapp.com/attachments/747443084274696214/1107800582850355271/The_Desperate_Garden.wld_2.bak

And, just in case, here is a screenshot of the loading bar outside the boundaries of its box (I was unable to capture it in the offscreen stage):
![Screenshot 2023-05-15 8 20 28 PM](https://github.com/TEdit/terraria-map-editor-web/assets/91434279/55449589-3416-4280-9851-4ce6ea827165)

**Comment by RussDev7** [comment]
Please know, the site version of TEdit is still pre-1.4.4.
